#!/bin/sh -e

check() {
	if [ "$(id -u)" -ne "0" ]; then
		echo '-! Superuser permissions are required, please launch again as root.'
		exit 1
	fi
}

get() {
	check

	if grep -w "$1" /etc/blx/blx@banned > /dev/null 2>&1; then
		echo "-> $1 is currently banned."
		exit 0
	fi

	if grep -w "$1" /etc/blx/blx@installed > /dev/null 2>&1; then
		echo "-> $1 is already installed."
		exit 0
	fi

	echo "-> Checking repo for $1..."
	if ! [ -d "$REPO/$1" ]; then
		echo "-! Package $1 not found!"
		exit 1
	fi
	cd "$REPO/$1"

	if [ -f "blx@tags" ]; then
		echo "-> Checking for banned tags..."
		while read -r CHECKTAG; do
			if grep -w "$CHECKTAG" /etc/blx/tag/blx@tag@banned > /dev/null 2>&1; then
				echo "-> $1 is currently associated with the tag $CHECKTAG, which is banned."
				exit 0
			fi
		done < blx@tags
	fi
	
	echo "--> Package found! Downloading $1..."
	./blx@get
	
	if [ -f "blx@depends" ]; then
		echo "-> Package is calling for dependencies..."
		while read -r DEPENDS; do
			$0 get "$DEPENDS"
		done < blx@depends
	fi

	echo "--> Installing $1... "
	./blx@add
	echo "$1" >> /etc/blx/blx@installed

	echo "-> Successfully installed $1!"
}

add() {
	check

	if grep -w "${PWD##*/}" /etc/blx/blx@banned > /dev/null 2>&1; then
		echo "-> ${PWD##*/} is currently banned."
		exit 0
	fi

	if grep -w "${PWD##*/}" /etc/blx/blx@installed > /dev/null 2>&1; then
                echo "-> ${PWD##*/} is already installed."
                exit 0
        fi

	if [ -f "blx@tags" ]; then
                echo "-> Checking for banned tags..."
                while read -r CHECKTAG; do
                        if grep -w "$CHECKTAG" /etc/blx/tag/blx@tag@banned > /dev/null 2>&1; then
                                echo "-> ${PWD##*/} is currently associated with the tag $CHECKTAG, which is banned."
                                exit 0
                        fi
                done < blx@tags
        fi

	echo "--> Checking if anything needs to be downloaded..."
	if [ -f "get" ]; then
		echo "--> Found instructions for download!"
		./blx@get
	fi
	
	if [ -f "blx@depends" ]; then
		echo "-> Package is calling for dependencies..."
		while read -r DEPENDS; do
			$0 get "$DEPENDS"
		done < blx@depends
	fi

	echo "--> Installing ${PWD##*/}..."
	./blx@add
	echo "${PWD##*/}" >> /etc/blx/blx@installed

	echo "-> Successfully installed ${PWD##*/}!"
}

remove() {
	check

        if ! grep -w "$1" /etc/blx/blx@installed > /dev/null 2>&1; then
                echo "-! Package $1 not installed!"
                exit 1
        fi

	echo "-> Finding package $1..."
	if ! [ -d "$REPO/$1" ]; then
		echo "-! Didn't find source directory!"
		exit 1
	fi
	cd "$REPO/$1"

	echo "--> Package found! Removing $1..."
	./blx@remove

	touch /etc/blx/blx@installed-tmp
	grep -v "$1" /etc/blx/blx@installed > /etc/blx/blx@installed-tmp || true 
	rm /etc/blx/blx@installed 
	mv /etc/blx/blx@installed-tmp /etc/blx/blx@installed

	echo "-> Successfully removed $1!"
}

delete() {
	check
	
	if grep -w "$1" /etc/blx/blx@installed > /dev/null 2>&1; then
		$0 remove "$1"
	fi
	
	echo "-> Deleting remaining files..."
	if [ -f "$REPO/$1/blx@delete" ]; then
		cd "$REPO/$1"
		./blx@delete || true
	fi

	echo "-> Files have been deleted!"
}

update() {
	check
	echo "-> Updating repositories..."
	cd "$REPO"
	git pull
	echo "-> Finished!"
}

ban() {
	check

	if grep -w "$1" /etc/blx/blx@banned > /dev/null 2>&1; then
		echo "-> $1 is already banned."
		exit 0
	fi
	
	if grep -w "$1" /etc/blx/blx@installed > /dev/null 2>&1; then
		$0 remove "$1"
	fi

	echo "-> Banning package $1..."
	echo "$1" >> /etc/blx/blx@banned
	echo "-> Successfully banned $1 from installing!"
}

unban() {
	check

	if ! grep -w "$1" /etc/blx/blx@banned > /dev/null 2>&1; then
		echo "-! $1 isn't banned!"
		exit 1
	fi

	echo "-> Unbanning package $1..."
	touch /etc/blx/blx@banned-tmp
	grep -v "$1" /etc/blx/blx@banned > /etc/blx/blx@banned-tmp || true 
	rm /etc/blx/blx@banned 
       	mv /etc/blx/blx@banned-tmp /etc/blx/blx@banned
	echo "-> $1 is now installable!"
}

info() {
	if ! [ -d "$REPO/$1" ]; then
		echo "-! Package $1 not found!"
		exit 1
	fi
	cd "$REPO/$1"

	echo "Name: $1"
	if [ -f "blx@author" ]; then
		echo "Author: $(cat blx@author)"
	fi

	if [ -f "blx@description" ]; then
		echo "Description: $(cat blx@description)"
	fi

	if [ -f "blx@depends" ]; then
		echo "Depends: $(echo $(cat blx@depends))"
	fi

	if [ -f "blx@tags" ]; then
		echo "Tags: $(echo $(cat blx@tags))"
	fi
}

setup() {
	check

	echo "-> Checking for Blocks directory..."
	if ! [ -d "/etc/blx" ]; then
		echo "--> Blocks directory not found! Creating one..."
		mkdir /etc/blx
	fi

	echo "-> Checking for database files..."
	if ! [ -f "/etc/blx/blx@installed" ]; then
		echo "--> Installed package database not found! Creating file..."
		touch /etc/blx/blx@installed
	fi
	if ! [ -f "/etc/blx/blx@banned" ]; then
		echo "--> Banned package database not found! Creating file..."
		touch /etc/blx/blx@banned
	fi
	
	echo "-> Checking for Modulus repositories..."
	if ! [ -d "/etc/blx/repo" ]; then
		echo "--> Modulus repositories not found! Cloning..."
		git clone https://github.com/moduluslinux/repo /etc/blx/repo
	fi

	echo "-> Checking for tag subsystem,,,"
	if ! [ -d "/etc/blx/tag" ]; then 
		echo "--> Tag subsystem not found! Setting up directory..."
		mkdir /etc/blx/tag
	fi
	if ! [ -f "/etc/blx/tag/blx@tag@banned" ]; then
		echo "--> Banned tag database not found! Creating file..."
		touch /etc/blx/tag/blx@tag@banned
	fi

	echo "-> Checking for Blocks config file..."
	if ! [ -f "/etc/blx/blx@config" ]; then
		echo "-> Config file not found! Using the default..."
		cat > /etc/blx/blx@config << EOF
#!/bin/sh -e
# Blocks Package Manager Configuration
# This is a pre-run script that will be executed when Blocks is launched.

# REPO represents where the Repository and all of the packages it contains
# are located on the system.
REPO="/etc/blx/repo/main"

# CFLAGS represents the options of the C compiler, and CXX flags represent
# the options of the C++ compiler (mirroring CFLAGS by default).
# [Note: -O3 is not a 0 (zero), it is an O.]
CFLAGS="-O3 -march=native"
CXXFLAGS="$CFLAGS"

# MAKEFLAGS represent the options of the Make build system. By default, 
# it is only set to compile the software on all cores.
MAKEFLAGS="-j$(nproc)"

# TARFLAGS specify how the archive should be extracted. By default, it
# only extracts the file with no verbose output (to enable verbose output,
# add 'v').
TARFLAGS="xf"
EOF
	fi

	echo "-> Finished! Blocks should be ready!"
}

tag() {
	get() {
		echo "-> Finding packages in $1..."
		cd "$REPO"
		for PACKAGE in */ ; do
			cd "$REPO/$PACKAGE"
			if grep -w "$1" blx@tags > /dev/null 2>&1; then
			       $0 get "${PWD##*/}" 
			fi
		done		
	}

	remove() {
		echo "-> Finding packages in $1..."
		cd "$REPO"
		for PACKAGE in */ ; do
			cd "$REPO/$PACKAGE"
			if grep -w "$1" blx@tags > /dev/null 2>&1; then
				if grep -w "${PWD##*/}" /etc/blx/blx@installed > /dev/null 2>&1; then
					$0 remove "${PWD##*/}"
				fi
			fi
		done
	}

	delete() {
		echo "-> Finding packages in $1..."
		cd "$REPO"
		for PACKAGE in */ ; do
			cd "$REPO/$PACKAGE"
			if grep -w "$1" blx@tags > /dev/null 2>&1; then
				if grep -w "${PWD##*/}" /etc/blx/blx@installed > /dev/null 2>&1; then
					$0 delete "${PWD##*/}"
				fi
			fi
		done
	}

	search() {
		cd "$REPO"
		for PACKAGE in */ ; do
			cd "$REPO/$PACKAGE"
			if grep -w "$1" blx@tags > /dev/null 2>&1; then
				echo "${PWD##*/}"
			fi
		done
	}

	ban() {
		if grep -w "$1" /etc/blx/tag/blx@tag@banned > /dev/null 2>&1; then
                	echo "-> Tag $1 is already banned."
                	exit 0
        	fi
		
		echo "-> Checking for any installed packages in $1..."
		cd "$REPO"
		for PACKAGE in */ ; do
			cd "$REPO/$PACKAGE"
			if grep -w "$1" blx@tags > /dev/null 2>&1; then
				if grep -w "${PWD##*/}" /etc/blx/blx@installed > /dev/null 2>&1; then
					$0 remove "${PWD##*/}"
        		fi
			fi
		done

		echo "-> Banning tag $1..."
		echo "$1" >> /etc/blx/tag/blx@tag@banned
		echo "-> Successfully banned the $1 tag!"
	}

	unban() {
		check

        	if ! grep -w "$1" /etc/blx/tag/blx@tag@banned > /dev/null 2>&1; then
                	echo "-! Tag $1 isn't banned!"
                	exit 1
        	fi

        	echo "-> Unbanning tag $1..."
        	touch /etc/blx/tag/blx@tag@banned-tmp
        	grep -v "$1" /etc/blx/tag/blx@tag@banned > /etc/blx/tag/blx@tag@banned-tmp || true
        	rm /etc/blx/tag/blx@tag@banned
        	mv /etc/blx/tag/blx@tag@banned-tmp /etc/blx/tag/blx@tag@banned
        	echo "-> Tag $1 can now be used!"
	}

	help() {
		echo "-> Blocks Tag Subsystem (blx tag)"
		echo "get: Download and install the packages that contain this specific tag."
		echo "remove: Remove all packages containing the tag, but keep the files."
		echo "delete: Clean all of the package files that contain the tag, and remove the packages if installed."
		echo "search: List all packages with the specified tag."
		echo "ban: Prevent any package with that specific tag from installing completely, even as a dependency."
		echo "unban: Revert the changes and allow the use of the specified tag again."
		echo "help: Currently being displayed, informs what each command does in the Tagging system."
	}

	if ! [ "$1" = "" ]; then
		$1 "$2"
	else
		help
	fi
}	

help() {
	echo '-> Blocks Package Manager (blx)'
	echo 'get: Download and install a package from the repositories.'
	echo 'add: Install an external package in the current directory.'
	echo 'remove: Remove a package from your system, but keep the files.'
	echo 'delete: Clean all of the package files, and remove package if not already done.'
	echo 'update: Update all of the packages and refresh the repositories.'
	echo 'ban: Prevent a package from installing completely, even as a dependency.'
	echo 'unban: Revert the changes and allow a package to be installed again.'
	echo 'info: Display the information for a specific package in the repositories.'
	echo 'setup: Sets up Blocks directory structure and repositories.'
	echo 'tag: A grouping subsystem for organization and effeciency (check blx tag help).'
	echo 'help: Currently being displayed, informs what each command does in Blocks.'
}

if [ -f "/etc/blx/blx@config" ]; then
	cd /etc/blx
	# shellcheck source=/dev/null
	. ./blx@config
fi

if ! [ "$1" = "" ]; then
	$1 "$2" "$3"
else
	help
fi
